language: generic 
sudo: required
services: 
  - docker

before_install:
  - docker build -t blatsosinf/docker-react-demo -f Dockerfile.dev .

script:
  - docker run -e CI=true blatsosinf/docker-react-demo npm run test